# Changes here will be overwritten by Copier
_commit: 939bd34
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: js
add_wiki: false
email: dev@1kbgz.com
github: 1kbgz
project_description: Easy benchmarking
project_name: benched
python_version_primary: '3.11'
team: the benched authors
